name: build

on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
      - 'update.json'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2
      with:
        fetch-depth: 0

    - name: Set variables
      run: |
        COMMIT_NUM=$(git rev-list --count HEAD)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        VERSION=$(jq -r .version update.json)
        ZIP_NAME=SAN_$VERSION-$COMMIT_NUM-$COMMIT_HASH
        
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

    - name: Create zips
      run: |
        # Create dummy zip
        cd module/dummy_zip
        cp -r ../META-INF .
        zip -r dummy.zip *
        mv dummy.zip ../
        
        # Create module zip
        cd ../
        zip -r "$ZIP_NAME" *

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: |
          module/
          !module/dummy_zip

    - name: Create release
      if: github.ref_type == 'tag'
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
        body: ${{ env.CHANGELOG }}
        draft: false
        files: module/${{ env.ZIP_NAME }}