name: build

on:
  push:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
  pull_request:
    branches:
      - master
    paths:
      - '.github/workflows/build.yml'
      - 'module/**'
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set variables
      id: setup
      run: |
        COMMIT_NUM=$(git rev-list --count HEAD)
        COMMIT_HASH=$(git rev-parse --short HEAD)
        VERSION=$(grep '^version=' module/module.prop | cut -d '=' -f 2)
        ZIP_NAME=SNA_$VERSION-$COMMIT_NUM-$COMMIT_HASH

        echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV

    - name: Create dummy zip
      run: |
        cd module
        zip -j dummy.zip module.prop

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.ZIP_NAME }}
        path: module/